<a href="https://colab.research.google.com/github/CryTechno/DIP/blob/main/Intro_to_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Початок роботи з бібліотекою Numpy

ВИКОНАВ СТУДЕНТ РОГОЖНІКОВ РОМАН АНДРІЙОВИЧ ПБ-21МП

У даній лабораторній роботі розглянуто наступний функціонал бібліотеки Numpy:
1. Створення масиву.
2. Відображення масивів .
3. Базові операції з масивами.

## Імпорт бібліотек та пакетів

Завантажуємо бібліотеку numpy та використаємо скорочення np.

In [5]:
import numpy as np

# Завдання
## 1. Створити двомірний нульовий масив розміром 11х11 та заповнити його діагоналі одиницями.

1.1. Задати розмір масиву

In [6]:
size = 11

1.2. Створити нульовий масив заданого розміру

In [7]:
arr = np.zeros((size,size))

1.3 Надрукувати створений масив

In [8]:
print(arr)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


1.4 Змінити діагоналі за допомогою двох циклів

In [9]:
for i in range(size):
	for j in range(size):
		if (i==j):
			arr[i][j] = 1
		elif ((i+j)==(size-1)):
			arr[i][j] = 1

1.5 Вивести створений масив

In [10]:
print(arr)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


## 2. Засобами NumPy створити вертикальні та горизонтальні зображення градієнту в обидва боки (поступове збільшення яскравості на зображенні).

Приклад зображення градієнту
<img src="./assignments/horizontal_grad.jpg" height="200" width="200">

### Горизонтальний градієнт

2.1 Створити нульовий масив розміром 255х255

In [11]:
horizontal_gradient1 = np.zeros((255,255))

2.2 Визначити розміри масиву

In [12]:
w = horizontal_gradient1.shape[0]
h = horizontal_gradient1.shape[1]
print(w)


255


2.3 Поелементно змінити яскравості кожного пікселя

In [13]:
s = 0
for i in range(w):  
    s=s+1
    for j in range(h):    
        horizontal_gradient1[j][i] = s

2.4 Записати зображення засабами OpenCV

In [14]:
import cv2
cv2.imwrite('horizontal_grad1.jpg', horizontal_gradient1)

True

2.5 Аналогічно створити горизонтальний градієнт в інший бік

In [15]:
horizontal_gradient2 = np.zeros((255,255))

w = horizontal_gradient2.shape[1]
h = horizontal_gradient2.shape[0]
s = 0
for i in range(w):
    s=s+1
    for j in range(h):
        horizontal_gradient2[j][-i] = s 
        
cv2.imwrite('horizontal_grad2.jpg', horizontal_gradient2)

True

### Вертикальний градієнт

2.6 Створити нульовий масив розміром 255х255

In [16]:
vertical_gradient1 = np.zeros((255,255))

2.7 Визначити розміри масиву

In [17]:
w = vertical_gradient1.shape[1]
h = vertical_gradient1.shape[0]

2.8 Поелементно змінити яскравості кожного пікселя

In [18]:
s = 0
for i in range(w):
    s=s+1
    for j in range(h):
        vertical_gradient1[i][j] = s

2.9 Записати зображення засабами OpenCV

In [19]:
cv2.imwrite('vertical_grad1.jpg', vertical_gradient1)

True

2.10 Аналогічно створити горизонтальний градієнт в інший бік

In [20]:
vertical_gradient2 = np.zeros((255,255))
w = vertical_gradient2.shape[1]
h = vertical_gradient2.shape[0]
s = 0
for i in range(h):
    s=s+1
    for j in range(w):
        vertical_gradient2[-i][j] = s
        
cv2.imwrite('vertical_grad2.jpg', vertical_gradient2)


True